sudo: required
services:
  - docker

before_install:
  - docker build -t dockyuse122/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dockyuse122/docker-react npm run test -- --coverage

